### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference in container

### ISSUE THREAD

**Issue by jeffabailey** [akamai/cli#116] opened 2020-12-23 18:10 UTC
The following error occurs within a Jenkins 2 build pipeline when executing this command.

If I run this command locally without an .edgerc this error does not occur.

```
akamai help
```

10:03:29  + akamai help
10:03:29  panic: runtime error: invalid memory address or nil pointer dereference
10:03:29  [signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x560c8fc662d8]
10:03:29  
10:03:29  goroutine 1 [running]:
10:03:29  main.saveConfig(0x560c8fc77a64, 0x3)
10:03:29  	/gopath/src/github.com/akamai/cli/config.go:82 +0xf8
10:03:29  main.migrateConfig()
10:03:29  	/gopath/src/github.com/akamai/cli/config.go:151 +0xaf
10:03:29  main.exportConfigEnv()
10:03:29  	/gopath/src/github.com/akamai/cli/config.go:191 +0x36
10:03:29  main.main()
10:03:29  	/gopath/src/github.com/akamai/cli/akamai.go:38 +0x89

**Comment by ellenbluth** [comment] 2020-12-23 21:23
Hi Jeff - Thank you for reaching out to us with this issue, we see this and are working to reproduce this issue.  Due to the holiday week, you can expect to hear back from us during the week of 12/28.

**Comment by rodriguise** [comment] 2020-12-25 01:19
The issue is a essentially a "rigged" race condition.

in `cli/akamai.go` 
   39 [`saveConfig()`](https://github.com/akamai/cli/blob/22e9631c1306bffe67c2943276f22d116b2aa9e2/akamai.go#L38) is called before 
   40 [`createApp()`](https://github.com/akamai/cli/blob/22e9631c1306bffe67c2943276f22d116b2aa9e2/akamai.go#L39)

If `saveConfig` fails at [`akamai/config.go:80`](https://github.com/akamai/cli/blob/22e9631c1306bffe67c2943276f22d116b2aa9e2/config.go#L80) it attempts to print the error to `akamai-cli.App.Writer` which unfortunately is not initialized until `cli/akamai.go:40`

The only way that I can see this happening is because when running in Jenkins it cannot write to the config file usually at `/home/{username}/.akamai-cli/config` which could be for any number of reasons, but most likely because the path does not exist. 

My recommendation would be either:

1. check that akami-cli.App.Writer` is not `nil`
2. gracefully handle the panic
3. detect that there is no home path and redirect the config to `/tmp`

**Comment by lkowalsk-akamai-com** [comment] 2021-03-26 10:54
Hi @jeffabailey, this issue should be fixed now. Please try with latest release and close the ticket.

**Closed** 2021-03-26 15:43 UTC
