### ISSUE TITLE
plugin installs fail (CentOS 8): "Unable to download binary: Unable to build binary (gtm)."

### ISSUE THREAD

**Issue by lmgray** [akamai/cli#131] opened 2021-07-19 20:56 UTC
We have a CenOS 8 docker build that tries to install akamai cli -- plugin installation started failing between 7/1 and 7/2:

```
+ akamai install gtm --force
[INFO] Installing Akamai CLI Plugins...
Attempting to fetch command from https://github.com/akamai/cli-gtm.git...
Attempting to fetch command from https://github.com/akamai/cli-gtm.git...... [OK]

Installing...
Installing...... [WARN]

Unable to build binary (gtm).
Downloading binary...
Downloading binary...... [FAIL]

Unable to download binary: Unable to build binary (gtm).
The command '/bin/sh -c bash -x ${toolsDir}/centos-setup-docker-image.sh' returned a non-zero code: 1
```

A couple of posts I found suggested this might be a \`golang\` version problem, so I tried the latest version (1.16.6) instead of the one in CentOS yum repo (1.15.?) but having the same problem...  This is in the context of a bigger (Jenkins JNLP agent) build, but I'm able to reproduce the problem with the following small Dockerfile:

```
FROM centos:8

RUN dnf install -y python3
RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3
RUN pip install httpie httpie-edgegrid

RUN curl -sSLO https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
RUN ln -s /usr/local/go/bin/go /usr/local/bin
RUN go version

RUN curl -sS -J -L -o /usr/local/bin/akamai https://github.com/akamai/cli/releases/download/1.1.5/akamai-1.1.5-linuxamd64
RUN chmod +x /usr/local/bin/akamai
RUN akamai install gtm
RUN akamai install purge
```

Any ideas would be appreciated!

**Comment by lmgray** [comment] 2021-07-20 16:19
I've worked around this by changing out build to download the standalone binaries from the sub-command repos releases, but still interested in what changed and how to use `akamai install ...` to install "plugins"

**Comment by robertolopezlopez** [comment] 2022-04-11 06:25
Hi @lmgray ,

Sorry for our late answer. I am trying to reproduce your issue. When I try to use your dockerfile, I am getting some errors. After some googling I have ended up with the following dockerfile, which allows me to reproduce your very same error:
```docker
FROM centos:8

RUN sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
RUN sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*
RUN dnf install -y python3
RUN curl -sS https://bootstrap.pypa.io/pip/3.6/get-pip.py | python3
RUN pip install httpie httpie-edgegrid

RUN curl -sSLO https://golang.org/dl/go1.16.6.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go1.16.6.linux-amd64.tar.gz
RUN ln -s /usr/local/go/bin/go /usr/local/bin
RUN go version

RUN curl -sS -J -L -o /usr/local/bin/akamai https://github.com/akamai/cli/releases/download/1.1.5/akamai-1.1.5-linuxamd64
RUN chmod +x /usr/local/bin/akamai
RUN akamai install gtm
RUN akamai install purge
```
![image](https://user-images.githubusercontent.com/1519467/162676255-1a9df28c-bd98-47ed-aa24-329e0e4ac1fd.png)
Assuming that this issue might be already fixed since you created this issue, I have replaced that URI with the one corresponding to our latest release ([v1.4.1](https://github.com/akamai/cli/releases/tag/v1.4.1)):
![image](https://user-images.githubusercontent.com/1519467/162676527-02194f83-bf1d-4f5e-8bd7-14466054fc7e.png)
And yes, it seems that this is fixed already.

I am closing this issue here but if you still have problems after the proposed CLI upgrade please do not hesitate on reopening.

Regards,

Roberto

**Closed by robertolopezlopez** 2022-04-11 06:25 UTC
