### ISSUE TITLE
"Unable to remove old executable" error still occurs in Powershell on Windows

### ISSUE THREAD

**Issue by stuartio** [akamai/cli#129] opened 2021-07-06 10:40 UTC
v1.2.1 states this was fixed as part of the release, and it works fine cmd.exe, but continues to throw the same error in Powershell v5 and v7.

**Comment by lkowalsk-akamai-com** [comment] 2021-07-06 11:17
Hi @stuartio,
I will close this issue as it is a duplicate of: https://github.com/akamai/cli/issues/125

**Closed by lkowalsk-akamai-com** 2021-07-06 11:17 UTC
