### ISSUE TITLE
unable to install akamai cli in RHEL linux

### ISSUE THREAD

**Issue by rageshns** [akamai/cli#22] opened 2017-09-15 02:24 UTC
![akamai cli issue](https://user-images.githubusercontent.com/507781/30463705-e8c7071c-99ea-11e7-8f33-ccc22614ebd9.PNG)

every time asking install prompt

**Comment by dshafik** [comment] 2017-09-20 17:28
I believe this is caused by #23, so I'm going to close it as a duplicate.

**Closed by dshafik** 2017-09-20 17:28 UTC
