### ISSUE TITLE
Installation experience for python packages

### ISSUE THREAD

**Issue by vreddhi** [akamai/cli#61] opened 2018-09-13 07:14 UTC
Can we have a more user-friendly experience for python packages? 

There are instances wherein users have python 2.7 and it is better if CLI can error out with a message if the required version doesn't match with requirement.txt

similar issue is reported here https://github.com/akamai/cli-cps/issues/7

**Comment by dshafik** [comment] 2018-09-13 07:15
@vreddhi this is indeed a bug, the intention is that if the version in `cli.json` can't be met, a friendly error is output.

**Comment by vreddhi** [comment] 2018-10-18 06:03
Here is another instance of the issue.
https://github.com/akamai/cli-property-manager/issues/15

**Comment by lukaszczerpak** [comment] 2018-11-26 08:09
I think this is more generic that the CLI doesn't give any further details on what was the root cause. I got similar generic error message without any useful details for golang based CLI when I tried to install it: https://github.com/akamai/AkamaiOPEN-edgegrid-golang/issues/37

**Comment by robertolopezlopez** [comment] 2022-04-11 06:49
Hi @vreddhi ,

Checking with some old docker image with python 2.7:

![image](https://user-images.githubusercontent.com/1519467/162679030-af56933b-3f5e-4455-9233-8dbeb12ab4c8.png)
![image](https://user-images.githubusercontent.com/1519467/162679947-3e4fd234-8924-479e-ae73-3988daee0ae3.png)
![image](https://user-images.githubusercontent.com/1519467/162680081-f8469170-d40b-4d72-b5a2-104d9e80c800.png)
By the way, `property-manager` is a node.js package, not Python :-) In any case, I consider that the CLI error is quite explicit in recent releases.

Thus closing this issue now. If you disagree, please do not hesitate on reopening it.

Regards,

Roberto

**Closed by robertolopezlopez** 2022-04-11 06:49 UTC
